name: Weekly MMN Automation

on:
  schedule:
    # MMN_WebScraper: Every Thursday at 2:00 AM UTC (9:00 PM CST Wednesday, 10:00 PM CDT)
    - cron: '0 2 * * 4'
    # MMN_WebsiteUpdater: Every Thursday at 3:00 AM UTC (10:00 PM CST Wednesday, 11:00 PM CDT)
    - cron: '0 3 * * 4'

jobs:
  run-scraper:
    if: github.event.schedule == '0 2 * * 4'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # or your required version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run MMN_WebScraper
        run: python MMN_WebScraper.py

  run-updater:
    if: github.event.schedule == '0 3 * * 4'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # or your required version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run MMN_WebsiteUpdater
        run: python MMN_WebsiteUpdater.py
